version: '3'

services:  

  selenium:
    image: selenium/hub
    expose:
      - 4444
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5900:5900
    depends_on:
      - selenium
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 5901:5900
    depends_on:
      - selenium
    networks:
      - selenium-grid

networks:
  selenium-grid: